// <auto-generated />
using ESchool.Common.Enums;
using ESchool.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ESchool.DataAccess.Migrations
{
    [DbContext(typeof(ESchoolContext))]
    [Migration("20180329155750_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESchool.Common.Model.Institution.CityDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.Property<DateTime>("CreatersDate");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime?>("ModifierDate");

                    b.Property<int?>("ModifierId");

                    b.HasKey("Id");

                    b.ToTable("CityDbModel");
                });

            modelBuilder.Entity("ESchool.Common.Model.Institution.InstitutionDbModel", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("CityId");

                    b.Property<DateTime>("CreatersDate");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime?>("ModifierDate");

                    b.Property<int?>("ModifierId");

                    b.Property<string>("SchoolAdress");

                    b.Property<int>("SchoolNumber");

                    b.HasKey("Id");

                    b.ToTable("InstutionDbModels");
                });

            modelBuilder.Entity("ESchool.Common.Model.SubjectOfInstuctions.SubjectOfInstructionsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatersDate");

                    b.Property<int>("CreatorId");

                    b.Property<string>("InstructionName");

                    b.Property<DateTime?>("ModifierDate");

                    b.Property<int?>("ModifierId");

                    b.HasKey("Id");

                    b.ToTable("SubjectOfInstructionsDbModels");
                });

            modelBuilder.Entity("ESchool.Common.Model.Users.AccauntDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatersDate");

                    b.Property<int>("CreatorId");

                    b.Property<string>("Email");

                    b.Property<bool>("IsBanned");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Loggin");

                    b.Property<DateTime?>("ModifierDate");

                    b.Property<int?>("ModifierId");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("AccauntDbModels");
                });

            modelBuilder.Entity("ESchool.Common.Model.Users.AccauntSettingsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccauntId");

                    b.Property<int?>("Age");

                    b.Property<int?>("ClassId");

                    b.Property<DateTime>("CreatersDate");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime?>("ModifierDate");

                    b.Property<int?>("ModifierId");

                    b.Property<string>("Patronymic");

                    b.Property<int?>("SchoolId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AccauntId")
                        .IsUnique();

                    b.ToTable("AccauntSettingsDbModels");
                });

            modelBuilder.Entity("ESchool.Common.Model.Institution.InstitutionDbModel", b =>
                {
                    b.HasOne("ESchool.Common.Model.Institution.CityDbModel", "City")
                        .WithMany("InstitutionsCollection")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ESchool.Common.Model.Users.AccauntSettingsDbModel", b =>
                {
                    b.HasOne("ESchool.Common.Model.Users.AccauntDbModel", "Accaunt")
                        .WithOne("AccauntSettings")
                        .HasForeignKey("ESchool.Common.Model.Users.AccauntSettingsDbModel", "AccauntId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
